version: "3.9"
services:
  # redis
  redis:
    image: redis
    container_name: ${PROJECT_NAME}_redis

  # Databases
  postgres_db:
    image: postgres
    volumes:
     - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    container_name: ${PROJECT_NAME}_postgres_db

  # Django app
  server:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/project
    image: server:django
    container_name: ${PROJECT_NAME}_container
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres_db

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A server worker -l INFO
    volumes:
      - .:/project
    container_name: ${PROJECT_NAME}_celery
    depends_on:
      - redis
      - server
      - postgres_db
