version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/django
    image: web:django
    container_name: django_project
    command: python manage.py runserver 0.0.0.0:8000