version: '3.9'

services:
  server:
    build: .
    volumes:
    - .:/opt/project
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      - db
    container_name: ${PROJECT_NAME}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${PROJECT_NAME}_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
